# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-29 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='logo',
        ),
    ]
