# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-29 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240629_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facilitymanager',
            name='role',
        ),
        migrations.RemoveField(
            model_name='facilitymanager',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='FacilityManager',
        ),
    ]
