# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-29 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240629_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='testing_password', max_length=100),
        ),
    ]
